패키지 설치 (mxnet, gluonnlp)

In [1]:
!pip install mxnet-cu100
!pip install gluonnlp

     |████████████████████████████████| 540.1MB 31kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1
     |████████████████████████████████| 245kB 18.1MB/s 
  Created wheel for gluonnlp: filename=gluonnlp-0.8.0-cp36-none-any.whl size=292704 sha256=6d4ef2faeca258d8b30c2330c639a82e7635bb2d8e07c83b888105b3d58fe854
  Stored in directory: /root/.cache/pip/wheels/28/ff/33/d73801f242fb93c02f2076f81232fcb9a29305480cc42c5454
Successfully built gluonnlp


In [0]:
import mxnet as mx
from mxnet import nd, autograd
import gluonnlp as nlp

In [3]:
mx.__version__

'1.5.0'

In [4]:
nlp.__version__

'0.8.0'

데이터 생성

In [5]:
x1 = nd.random.normal(shape=(1,10))
print(x1)


[[ 2.2122064   0.7740038   1.0434403   1.1839255   1.8917114  -1.2347414
  -1.771029   -0.45138445  0.57938355 -1.856082  ]]
<NDArray 1x10 @cpu(0)>


In [6]:
## reshape
x2 = nd.arange(10).reshape(2,5)
print(x2)


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>


In [8]:
##transpose
x2_1 = x2.swapaxes(0,1)
print(x2_1)


[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]]
<NDArray 5x2 @cpu(0)>


 GPU / CPU  할당

In [9]:
##GPU에 할당
x3= nd.random.normal(shape=(2,10), ctx=mx.gpu())
print(x3)


[[-1.3204551   0.68232244 -0.9858383   0.0199282   0.7842404   0.50066984
  -1.0283493   0.98445714  0.23791966  0.5675242 ]
 [ 0.416008    1.2724396   0.90007704  0.43224135 -0.04885176  0.00976894
  -0.6189104  -0.59411055 -0.7401756  -0.29974517]]
<NDArray 2x10 @gpu(0)>


In [10]:
##GPU -> CPU 할당
x4 = x3.as_in_context(mx.cpu())
print(x4)


[[-1.3204551   0.68232244 -0.9858383   0.0199282   0.7842404   0.50066984
  -1.0283493   0.98445714  0.23791966  0.5675242 ]
 [ 0.416008    1.2724396   0.90007704  0.43224135 -0.04885176  0.00976894
  -0.6189104  -0.59411055 -0.7401756  -0.29974517]]
<NDArray 2x10 @cpu(0)>


Operation

In [11]:
##slice 연산
x5 = x4[:,:3]
print(x5)


[[-1.3204551   0.68232244 -0.9858383 ]
 [ 0.416008    1.2724396   0.90007704]]
<NDArray 2x3 @cpu(0)>


In [0]:
##Matrix 연산
### dot product
a = nd.arange(10).reshape(2,5)
b = nd.arange(10).reshape(5,2)
c = nd.dot(a, b)

In [13]:
print(a)


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>


In [14]:
print(b)


[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
<NDArray 5x2 @cpu(0)>


In [15]:
print(c)


[[ 60.  70.]
 [160. 195.]]
<NDArray 2x2 @cpu(0)>


In [0]:
##Batch matrix multiplication
a = nd.arange(30).reshape(5,2,3)
b = nd.arange(60).reshape(5,3,4)
c = nd.batch_dot(a, b)

In [18]:
print(a)


[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]]

 [[24. 25. 26.]
  [27. 28. 29.]]]
<NDArray 5x2x3 @cpu(0)>


In [19]:
print(b)


[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]

 [[24. 25. 26. 27.]
  [28. 29. 30. 31.]
  [32. 33. 34. 35.]]

 [[36. 37. 38. 39.]
  [40. 41. 42. 43.]
  [44. 45. 46. 47.]]

 [[48. 49. 50. 51.]
  [52. 53. 54. 55.]
  [56. 57. 58. 59.]]]
<NDArray 5x3x4 @cpu(0)>


In [20]:
print(c)


[[[  20.   23.   26.   29.]
  [  56.   68.   80.   92.]]

 [[ 344.  365.  386.  407.]
  [ 488.  518.  548.  578.]]

 [[1100. 1139. 1178. 1217.]
  [1352. 1400. 1448. 1496.]]

 [[2288. 2345. 2402. 2459.]
  [2648. 2714. 2780. 2846.]]

 [[3908. 3983. 4058. 4133.]
  [4376. 4460. 4544. 4628.]]]
<NDArray 5x2x4 @cpu(0)>


Numpy로 변환

In [0]:
d = c.asnumpy()

In [22]:
d

array([[[  20.,   23.,   26.,   29.],
        [  56.,   68.,   80.,   92.]],

       [[ 344.,  365.,  386.,  407.],
        [ 488.,  518.,  548.,  578.]],

       [[1100., 1139., 1178., 1217.],
        [1352., 1400., 1448., 1496.]],

       [[2288., 2345., 2402., 2459.],
        [2648., 2714., 2780., 2846.]],

       [[3908., 3983., 4058., 4133.],
        [4376., 4460., 4544., 4628.]]], dtype=float32)